c-ares: Upgrade to 1.17.1 release
Forward port cmake-install-libcares.pc.patch, drop the need to install
pkgconfig files as its already being done by main Makefile

Signed-off-by: Khem Raj <raj.khem@gmail.com>

cherry picked from commit b65f2904191b8d309b3971d4e65c5e1701156b1c, to fix this
issue building nodejs v14:

../src/cares_wrap.cc:324:57: error: ‘ares_parse_caa_reply’ was not declared in this scope

That function was added to c-ares in version 1.17.0

Included in Honister.